DROP TABLE IF EXISTS county_contacts;

CREATE TABLE county_contacts (
   id   tinyint          NOT NULL DEFAULT  0,  PRIMARY KEY(id),
   web1      varchar(60) NOT NULL DEFAULT "",
   web2      varchar(60) NOT NULL DEFAULT "",
   facebook  varchar(60) NOT NULL DEFAULT "",
   twitter   varchar(60) NOT NULL DEFAULT "",
   instagram varchar(60) NOT NULL DEFAULT "",
   email     varchar(60) NOT NULL DEFAULT "",
   volunteer varchar(60) NOT NULL DEFAULT ""
);

INSERT INTO county_contacts (id) values (1);
INSERT INTO county_contacts (id) values (2);
INSERT INTO county_contacts (id) values (3);
INSERT INTO county_contacts (id) values (4);
INSERT INTO county_contacts (id) values (5);
INSERT INTO county_contacts (id) values (6);
INSERT INTO county_contacts (id) values (7);
INSERT INTO county_contacts (id) values (8);
INSERT INTO county_contacts (id) values (9);
INSERT INTO county_contacts (id) values (10);
INSERT INTO county_contacts (id) values (11);
INSERT INTO county_contacts (id) values (12);
INSERT INTO county_contacts (id) values (13);
INSERT INTO county_contacts (id) values (14);
INSERT INTO county_contacts (id) values (15);
INSERT INTO county_contacts (id) values (16);
INSERT INTO county_contacts (id) values (17);
INSERT INTO county_contacts (id) values (18);
INSERT INTO county_contacts (id) values (19);
INSERT INTO county_contacts (id) values (20);
INSERT INTO county_contacts (id) values (21);
INSERT INTO county_contacts (id) values (22);
INSERT INTO county_contacts (id) values (23);
INSERT INTO county_contacts (id) values (24);
INSERT INTO county_contacts (id) values (25);
INSERT INTO county_contacts (id) values (26);
INSERT INTO county_contacts (id) values (27);
INSERT INTO county_contacts (id) values (28);
INSERT INTO county_contacts (id) values (29);
INSERT INTO county_contacts (id) values (30);
INSERT INTO county_contacts (id) values (31);
INSERT INTO county_contacts (id) values (32);
INSERT INTO county_contacts (id) values (33);
INSERT INTO county_contacts (id) values (34);
INSERT INTO county_contacts (id) values (35);
INSERT INTO county_contacts (id) values (36);
INSERT INTO county_contacts (id) values (37);
INSERT INTO county_contacts (id) values (38);
INSERT INTO county_contacts (id) values (39);
INSERT INTO county_contacts (id) values (40);
INSERT INTO county_contacts (id) values (41);
INSERT INTO county_contacts (id) values (42);
INSERT INTO county_contacts (id) values (43);
INSERT INTO county_contacts (id) values (44);
INSERT INTO county_contacts (id) values (45);
INSERT INTO county_contacts (id) values (46);
INSERT INTO county_contacts (id) values (47);
INSERT INTO county_contacts (id) values (48);
INSERT INTO county_contacts (id) values (49);
INSERT INTO county_contacts (id) values (50);
INSERT INTO county_contacts (id) values (51);
INSERT INTO county_contacts (id) values (52);
INSERT INTO county_contacts (id) values (53);
INSERT INTO county_contacts (id) values (54);
INSERT INTO county_contacts (id) values (55);
INSERT INTO county_contacts (id) values (56);
INSERT INTO county_contacts (id) values (57);
INSERT INTO county_contacts (id) values (58);
INSERT INTO county_contacts (id) values (59);
INSERT INTO county_contacts (id) values (60);
INSERT INTO county_contacts (id) values (61);
INSERT INTO county_contacts (id) values (62);
INSERT INTO county_contacts (id) values (63);
INSERT INTO county_contacts (id) values (64);
INSERT INTO county_contacts (id) values (65);
INSERT INTO county_contacts (id) values (66);
INSERT INTO county_contacts (id) values (67);
INSERT INTO county_contacts (id) values (68);
INSERT INTO county_contacts (id) values (69);
INSERT INTO county_contacts (id) values (70);
INSERT INTO county_contacts (id) values (71);
INSERT INTO county_contacts (id) values (72);
INSERT INTO county_contacts (id) values (73);
INSERT INTO county_contacts (id) values (74);
INSERT INTO county_contacts (id) values (75);
INSERT INTO county_contacts (id) values (76);
INSERT INTO county_contacts (id) values (77);
INSERT INTO county_contacts (id) values (78);
INSERT INTO county_contacts (id) values (79);
INSERT INTO county_contacts (id) values (80);
INSERT INTO county_contacts (id) values (81);
INSERT INTO county_contacts (id) values (82);
INSERT INTO county_contacts (id) values (83);
